export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

import "bootstrap/dist/css/bootstrap.min.css";
import "../(members-only)/members.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="members-shell" data-theme="light">
        {children}
      </body>
    </html>
  );
}
