import { Schema, model, models } from "mongoose";

/// One block of an article.
///
/// The body is an ordered array of these rather than a single string of
/// markup, because the builder on the website manipulates blocks directly —
/// add, reorder, delete — and both readers (the public page and the iOS app)
/// render them by switching on `type`. A markup blob would have needed a
/// parser on each surface and a WYSIWYG that agreed with both of them.
///
/// `_id: false` because a block's identity is `id`, generated by the builder
/// and preserved across saves so reordering does not churn Mongo ids.

/// One picture inside a gallery block.
const GalleryImageSchema = new Schema(
  {
    imageKey: { type: String, default: "" },
    alt: { type: String, default: "" },
    caption: { type: String, default: "" },
    width: { type: Number, default: 0 },
    height: { type: Number, default: 0 },
  },
  { _id: false }
);

const NewsletterBlockSchema = new Schema(
  {
    id: { type: String, required: true },
    type: {
      type: String,
      required: true,
      enum: [
        "heading",
        "subheading",
        "paragraph",
        "list",
        "quote",
        "callout",
        "image",
        "gallery",
        "divider",
      ],
    },
    /// heading, subheading, paragraph, quote, callout.
    text: { type: String, default: "" },
    /// quote only — who said it.
    attribution: { type: String, default: "" },
    /// list only. An array rather than one newline-joined string, so nothing
    /// downstream has to agree on a separator to render or reorder it.
    items: { type: [String], default: undefined },
    /// list only — numbered rather than bulleted.
    ordered: { type: Boolean, default: undefined },
    /// callout only — note, highlight or warning.
    variant: { type: String, default: undefined },
    /// image only. The object key, never a URL: URLs into Garage are presigned
    /// and expire, so storing one would mean the article rots after an hour.
    /// Every read mints a fresh signature from this key.
    imageKey: { type: String, default: "" },
    caption: { type: String, default: "" },
    /// image only — photographer or source, printed small under the picture.
    credit: { type: String, default: "" },
    /// image only — how wide it runs: standard, wide, or full.
    layout: { type: String, default: undefined },
    /// Always written, even when the caption is empty. A caption is for
    /// everyone; alt text is for the people who cannot see the photo, and
    /// collapsing the two leaves them with nothing.
    alt: { type: String, default: "" },
    /// Intrinsic pixel size, recorded at upload. Lets both clients reserve the
    /// right box before the bytes land instead of reflowing the article
    /// underneath somebody who is already reading it.
    width: { type: Number, default: 0 },
    height: { type: Number, default: 0 },
    /// gallery only.
    images: { type: [GalleryImageSchema], default: undefined },
  },
  { _id: false }
);

const NewsletterSchema = new Schema(
  {
    title: { type: String, required: true, trim: true },
    /// The public address: ttdg.org/newsletters/<slug>. Unique because it is
    /// the primary way anyone reaches an issue — from a share sheet, a text
    /// message, a link in the app — and two articles answering the same URL
    /// would make one of them unreachable.
    slug: { type: String, required: true, unique: true, index: true },
    /// One or two lines for the card and the link preview. Written for the
    /// card rather than lifted from the opening paragraph, which reads as a
    /// truncation.
    summary: { type: String, default: "" },
    category: {
      type: String,
      enum: ["chapter", "brotherhood", "professional", "service"],
      default: "chapter",
    },
    coverImageKey: { type: String, default: "" },
    coverAlt: { type: String, default: "" },
    blocks: { type: [NewsletterBlockSchema], default: [] },
    /// Drafts are visible only to the officers who can edit them. The public
    /// page, the feed in the app, and the share link all resolve published
    /// issues only — a half-written article must not be one guessed URL away.
    status: { type: String, enum: ["draft", "published"], default: "draft" },
    /// Stamped the first time it goes live and left alone afterwards, so
    /// fixing a typo three weeks later does not move the issue to the top of
    /// the feed.
    publishedAt: { type: Date, default: null },
    /// The byline. Defaults to the office rather than the person: the article
    /// is the chapter's, and next year's Corresponding Secretary inherits the
    /// archive.
    authorName: { type: String, default: "Corresponding Secretary" },
    createdBy: { type: Schema.Types.ObjectId, ref: "Member", required: true },
    updatedBy: { type: Schema.Types.ObjectId, ref: "Member", default: null },
    /// When the chapter was pushed about this issue. Set once, on the first
    /// publish, and checked before every send — an edit that re-saves a
    /// published article must not notify sixty people a second time.
    notifiedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

/// The feed's only read pattern: published issues, newest first.
NewsletterSchema.index({ status: 1, publishedAt: -1 });

if (process.env.NODE_ENV === "development" && models.Newsletter) {
  delete models.Newsletter;
}

const Newsletter = models.Newsletter || model("Newsletter", NewsletterSchema);
export default Newsletter;
